#----------This line of code will avoid warning while running selective test----------------- 
[pytest]
testpaths = tests
markers =
    smoke: Critical smoke tests
    regression: Regression test cases
    security: Security test cases
    e2e: End-to-end business flow tests